name: remote-smoke-pdf
on:
  workflow_dispatch: {}
  push:
    branches: [ develop ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    env:
      BASE_URL: ${{ secrets.DEV_BASE_URL }}   # напр. http://89.169.189.66
      TOKEN:    ${{ secrets.SMOKE_TOKEN }}    # smoke
      CART: >-
        {"cart":{"items":[{"model":"PO Base 1/1","width":800,"height":2000,"color":"Белый","qty":1}]}}
    steps:
      - name: Health 204
        run: |
          code=$(curl -sS -o /dev/null -w "%{http_code}" "$BASE_URL/api/health")
          echo "health: $code"
          test "$code" = "204"

      - name: Admin ping 200
        run: |
          code=$(curl -sS -H "Authorization: Bearer $TOKEN" -o /dev/null -w "%{http_code}" "$BASE_URL/api/admin/ping")
          echo "admin/ping: $code"
          test "$code" = "200"

      # ---------- Диагностические шаги для экспорта ----------
      - name: KP PDF
        run: |
          curl -sS -X POST \
               -H 'Content-Type: application/json' \
               -H "Authorization: Bearer $TOKEN" \
               -d "$CART" \
               "$BASE_URL/api/cart/export/doors/kp?format=pdf" \
               -D /tmp/headers -o /tmp/body || true
          echo "---- KP status ----"
          awk 'BEGIN{RS="\r\n\r\n";FS="\r\n"} NR==1{print $1; for(i=2;i<=NF;i++) print $i}' /tmp/headers
          echo "-------------------"
          # Убедимся, что 200 и pdf в заголовках
          grep -qi '^HTTP/1\.[01] 200' /tmp/headers
          grep -qi 'content-type:.*application/pdf' /tmp/headers

      - name: Invoice PDF
        run: |
          curl -sS -X POST \
               -H 'Content-Type: application/json' \
               -H "Authorization: Bearer $TOKEN" \
               -d "$CART" \
               "$BASE_URL/api/cart/export/doors/invoice?format=pdf" \
               -D /tmp/headers -o /tmp/body || true
          echo "---- Invoice status ----"
          awk 'BEGIN{RS="\r\n\r\n";FS="\r\n"} NR==1{print $1; for(i=2;i<=NF;i++) print $i}' /tmp/headers
          echo "------------------------"
          grep -qi '^HTTP/1\.[01] 200' /tmp/headers
          grep -qi 'content-type:.*application/pdf' /tmp/headers

      - name: Factory XLSX
        run: |
          curl -sS -X POST \
               -H 'Content-Type: application/json' \
               -H "Authorization: Bearer $TOKEN" \
               -d "$CART" \
               "$BASE_URL/api/cart/export/doors/factory?format=xlsx" \
               -D /tmp/headers -o /tmp/body || true
          echo "---- Factory status ----"
          awk 'BEGIN{RS="\r\n\r\n";FS="\r\n"} NR==1{print $1; for(i=2;i<=NF;i++) print $i}' /tmp/headers
          echo "------------------------"
          grep -qi '^HTTP/1\.[01] 200' /tmp/headers
          grep -Eqi 'content-type:.*(spreadsheetml|application/vnd.openxmlformats)' /tmp/headers
